### ISSUE TITLE
Error : object ‘gaussianff’ is not exported by 'namespace:VGAM'

### ISSUE THREAD

**Issue by xuzhougeng** [cole-trapnell-lab/monocle-release#188]
I try to install  monocle3_alpha  as described in http://cole-trapnell-lab.github.io/monocle-release/monocle3/

```R
devtools::install_github("cole-trapnell-lab/monocle-release", ref="monocle3_alpha")
```

But I come across the following problem

```R
* installing *source* package ‘monocle’ ...
** libs
g++ -std=gnu++11 -I"/home/wangjw/opt/sysoft/lib64/R/include" -DNDEBUG  -I"/home/wangjw/opt/sysoft/lib64/R/library/Rcpp/include" -I/usr/local/include   -fpic  -g -O2 -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/home/wangjw/opt/sysoft/lib64/R/include" -DNDEBUG  -I"/home/wangjw/opt/sysoft/lib64/R/library/Rcpp/include" -I/usr/local/include   -fpic  -g -O2 -c clustering.cpp -o clustering.o
g++ -std=gnu++11 -I"/home/wangjw/opt/sysoft/lib64/R/include" -DNDEBUG  -I"/home/wangjw/opt/sysoft/lib64/R/library/Rcpp/include" -I/usr/local/include   -fpic  -g -O2 -c landmark_selection.cpp -o landmark_selection.o
g++ -std=gnu++11 -shared -L/usr/local/lib64 -o monocle.so RcppExports.o clustering.o landmark_selection.o
installing to /home/wangjw/opt/sysoft/lib64/R/library/monocle/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** byte-compile and prepare package for lazy loading
Warning in rgl.init(initValue, onlyNULL) :
  RGL: unable to open X11 display
Warning: 'rgl_init' failed, running with rgl.useNULL = TRUE
Error : object ‘gaussianff’ is not exported by 'namespace:VGAM'
ERROR: lazy loading failed for package ‘monocle’
* removing ‘/home/wangjw/opt/sysoft/lib64/R/library/monocle’
* restoring previous ‘/home/wangjw/opt/sysoft/lib64/R/library/monocle’
Installation failed: Command failed (1)
···

Ths OS of my computer is "CentOS Linux release 7.4.1708 (Core) ", 

And the sessioninfo of my R before installing

```R
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS: /home/wangjw/opt/sysoft/lib64/R/lib/libRblas.so
LAPACK: /home/wangjw/opt/sysoft/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.0

```

And after running devtools::install_github, The sessioninfo is

```R
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.0       BiocInstaller_1.30.0 tools_3.5.0         
[4] withr_2.1.2          memoise_1.1.0        git2r_0.23.0        
[7] digest_0.6.15        devtools_1.13.
```

So does anyone have met the same problem? And how can I fix this problem

**Comment by XiaoliMa** [comment]
My system is macOS Sierra 10.12.16. R-version is 3.5.1, when I try to install the the Moncle 3, there some warnings and errors as following.
devtools::install_github("cole-trapnell-lab/L1-graph")

Downloading GitHub repo cole-trapnell-lab/L1-graph@master
from URL https://api.github.com/repos/cole-trapnell-lab/L1-graph/zipball/master
Installing L1Graph
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  '/private/var/folders/7s/c_q6bx6j6yscv0ft1gktxh_r0000gn/T/Rtmp0jIwsr/devtoolsa7c46d0c49b6/cole-trapnell-lab-L1-graph-c2a3f26'  \
  --library='/Library/Frameworks/R.framework/Versions/3.5/Resources/library' --install-tests 

* installing *source* package ‘L1Graph’ ...
** R
** tests
** byte-compile and prepare package for lazy loading
Note: possible error in 'principal_graph(X, C0, ': unused arguments (lambda = lambda, gamma = gamma, sigma = sigma) 
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (L1Graph)

I came to the same problem as above. There is the only VGAM_1.0.6 for mac OS and tried to installed it. There are still lots of errors: 

installing to /Library/Frameworks/R.framework/Versions/3.5/Resources/library/monocle/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** byte-compile and prepare package for lazy loading
Warning: package ‘DelayedArray’ was built under R version 3.5.1
Error : object ‘gaussianff’ is not exported by 'namespace:VGAM'
ERROR: lazy loading failed for package ‘monocle’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/monocle’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/monocle’
Installation failed: Command failed (1)

**Comment by Xiaojieqiu** [comment]
@XiaoliMa Please check out the solution I suggested above and let me know how it goes. Thanks

**Comment by xuzhougeng** [comment]
@Xiaojieqiu According to your suggestion, I download and install `VGAM v1.05`,  

```
> package.version("VGAM")
[1] "1.0-5
```
when I try to use `devtools::install_github("cole-trapnell-lab/monocle-release", ref="monocle3_alpha")` , I found that R will automatically start downloading `VGAM_1.0.6` which will cause the problem likes before.

```R
> devtools::install_github("cole-trapnell-lab/monocle-release", ref="monocle3_alpha")
Downloading GitHub repo cole-trapnell-lab/monocle-release@monocle3_alpha
from URL https://api.github.com/repos/cole-trapnell-lab/monocle-release/zipball/monocle3_alpha
Installing monocle
trying URL 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/src/contrib/VGAM_1.0-6.tar.gz'
Content type 'application/octet-stream' length 2585263 bytes (2.5 MB)
==================================================
downloaded 2.5 MB

Installing VGAM
'/home/wangjw/opt/sysoft/lib64/R/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpivOAd0/devtoolsacaf6e3d4f92/VGAM'  \
  --library='/home/wangjw/opt/sysoft/lib64/R/library' --install-tests 
....
Warning in rgl.init(initValue, onlyNULL) :
  RGL: unable to open X11 display
Warning: 'rgl_init' failed, running with rgl.useNULL = TRUE
Error : object ‘gaussianff’ is not exported by 'namespace:VGAM'
ERROR: lazy loading failed for package ‘monocle’
```

So I clone this repos into local with `git clone https://github.com/cole-trapnell-lab/monocle-release.git`, then I try install locally with the following commands

```bash
cd monocle-release
git checkout monocle3_alpha
cd ..
R CMD INSTALL monocle-release
```

And the message after I loading this packages is shown below 

```R
>library("monocle"
Warning messages:
1: In rgl.init(initValue, onlyNULL) : RGL: unable to open X11 display
2: 'rgl_init' failed, running with rgl.useNULL = TRUE 
> package.version("monocle")
[1] "2.99.1"
```
Is this means I successfully install monocle3?

**Comment by Xiaojieqiu** [comment]
@xuzhougeng Definitively, I think you have successfully installed Monocle3. Welcome to the world of Monocle 3!

**Comment by XiaoliMa** [comment]
I still failed to to install VGAM (1.05 version) on mac version Rstudio. I can only install 1.06 version, which is not right for monocle3.

**Comment by Xiaojieqiu** [comment]
seems like you don't know how to install VGAM 1.05 locally... please download VGAM 1.05 from the CRAN and install it manually using _

> R CMD INSTALL VGAM_1.0-5.tar.gz

in terminal 

link to download VGAM 1.05
https://cran.r-project.org/src/contrib/Archive/VGAM/VGAM_1.0-5.tar.gz

**Comment by XiaoliMa** [comment]
I installed you suggested, the error like this: 

> install.packages("~/Downloads/VGAM_1.0-5.tar.gz", repos = NULL, type = "source")
* installing *source* package ‘VGAM’ ...
** package ‘VGAM’ successfully unpacked and MD5 sums checked
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c VGAM_init.c -o VGAM_init.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c caqo3.c -o caqo3.o
gfortran   -fPIC  -g -O2  -c cqof.f -o cqof.o
make: gfortran: No such file or directory
make: *** [cqof.o] Error 1
ERROR: compilation failed for package ‘VGAM’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/VGAM’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/VGAM’
Warning in install.packages :
  installation of package ‘/Users/XiaoliMa/Downloads/VGAM_1.0-5.tar.gz’ had non-zero exit status

**Comment by Xiaojieqiu** [comment]
https://stackoverflow.com/questions/23916219/os-x-package-installation-depends-on-gfortran-4-8

**Comment by koenvandenberge** [comment]
Hi @Xiaojieqiu , the installation still errors with the older VGAM package you suggested:

```
> install.packages("~/Downloads/VGAM_1.0-5.tar.gz")
inferring 'repos = NULL' from 'pkgs'
* installing *source* package ‘VGAM’ ...
** package ‘VGAM’ successfully unpacked and MD5 sums checked
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c VGAM_init.c -o VGAM_init.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c caqo3.c -o caqo3.o
gfortran   -fPIC  -g -O2  -c cqof.f -o cqof.o
gfortran: warning: couldn’t understand kern.osversion ‘15.6.0
gfortran   -fPIC  -g -O2  -c ei.f -o ei.o
gfortran: warning: couldn’t understand kern.osversion ‘15.6.0
gfortran   -fPIC  -g -O2  -c fgam.f -o fgam.o
gfortran: warning: couldn’t understand kern.osversion ‘15.6.0
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c gautr.c -o gautr.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c lerchphi.c -o lerchphi.o
gfortran   -fPIC  -g -O2  -c lms.f -o lms.o
gfortran: warning: couldn’t understand kern.osversion ‘15.6.0
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c muxr3.c -o muxr3.o
gfortran   -fPIC  -g -O2  -c rgam.f -o rgam.o
gfortran: warning: couldn’t understand kern.osversion ‘15.6.0
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c rgam3.c -o rgam3.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c specfun3.c -o specfun3.o
gfortran   -fPIC  -g -O2  -c tyeepolygamma.f -o tyeepolygamma.o
gfortran: warning: couldn’t understand kern.osversion ‘15.6.0
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c tyeepolygamma3.c -o tyeepolygamma3.o
gfortran   -fPIC  -g -O2  -c vcall2.f -o vcall2.o
gfortran: warning: couldn’t understand kern.osversion ‘15.6.0
gfortran   -fPIC  -g -O2  -c vdigami.f -o vdigami.o
gfortran: warning: couldn’t understand kern.osversion ‘15.6.0
gfortran   -fPIC  -g -O2  -c veigen.f -o veigen.o
gfortran: warning: couldn’t understand kern.osversion ‘15.6.0
gfortran   -fPIC  -g -O2  -c vgam.f -o vgam.o
gfortran: warning: couldn’t understand kern.osversion ‘15.6.0
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c vgam3.c -o vgam3.o
gfortran   -fPIC  -g -O2  -c vlinpack1.f -o vlinpack1.o
gfortran: warning: couldn’t understand kern.osversion ‘15.6.0
gfortran   -fPIC  -g -O2  -c vlinpack2.f -o vlinpack2.o
gfortran: warning: couldn’t understand kern.osversion ‘15.6.0
gfortran   -fPIC  -g -O2  -c vlinpack3.f -o vlinpack3.o
gfortran: warning: couldn’t understand kern.osversion ‘15.6.0
gfortran   -fPIC  -g -O2  -c vmux.f -o vmux.o
gfortran: warning: couldn’t understand kern.osversion ‘15.6.0
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c vmux3.c -o vmux3.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c zeta3.c -o zeta3.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o VGAM.so VGAM_init.o caqo3.o cqof.o ei.o fgam.o gautr.o lerchphi.o lms.o muxr3.o rgam.o rgam3.o specfun3.o tyeepolygamma.o tyeepolygamma3.o vcall2.o vdigami.o veigen.o vgam.o vgam3.o vlinpack1.o vlinpack2.o vlinpack3.o vmux.o vmux3.o zeta3.o -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
installing to /Library/Frameworks/R.framework/Versions/3.5/Resources/library/VGAM/libs
** R
** data
*** moving datasets to lazyload DB
** demo
** inst
** byte-compile and prepare package for lazy loading
Creating a new generic function for ‘Rank’ in package ‘VGAM’
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (VGAM)
> devtools::install_github("cole-trapnell-lab/monocle-release", ref="monocle3_alpha")
Downloading GitHub repo cole-trapnell-lab/monocle-release@monocle3_alpha
from URL https://api.github.com/repos/cole-trapnell-lab/monocle-release/zipball/monocle3_alpha
Installing monocle
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5/VGAM_1.0-6.tgz'
Content type 'application/x-gzip' length 7852157 bytes (7.5 MB)
==================================================
downloaded 7.5 MB

Installing VGAM
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/ys/t9sslrsd1n3bfwzf3ycl6w740000gn/T/RtmpfVgs7R/devtools79ad78867368/VGAM'  \
  --library='/Library/Frameworks/R.framework/Versions/3.5/Resources/library'  \
  --install-tests 

* installing *binary* package ‘VGAM’ ...
* DONE (VGAM)
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/ys/t9sslrsd1n3bfwzf3ycl6w740000gn/T/RtmpfVgs7R/devtools79ad6f0de255/cole-trapnell-lab-monocle-release-3ff311b'  \
  --library='/Library/Frameworks/R.framework/Versions/3.5/Resources/library'  \
  --install-tests 

* installing *source* package ‘monocle’ ...
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I/usr/local/include   -fPIC  -Wall -g -O2 -c RcppExports.cpp -o RcppExports.o
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I/usr/local/include   -fPIC  -Wall -g -O2 -c clustering.cpp -o clustering.o
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I/usr/local/include   -fPIC  -Wall -g -O2 -c landmark_selection.cpp -o landmark_selection.o
landmark_selection.cpp:248:7: warning: unused variable 'num_proc' [-Wunused-variable]
  int num_proc = stoi(str_num_proc);
      ^
1 warning generated.
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o monocle.so RcppExports.o clustering.o landmark_selection.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.5/Resources/library/monocle/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** byte-compile and prepare package for lazy loading
Warning: package ‘DelayedArray’ was built under R version 3.5.1
Warning: package ‘IRanges’ was built under R version 3.5.1
Error : object ‘gaussianff’ is not exported by 'namespace:VGAM'
ERROR: lazy loading failed for package ‘monocle’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/monocle’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/monocle’
Installation failed: Command failed (1)
> 
```

**Comment by ondp15** [comment]
Hello, 

I followed the commands from xuzhougeng and everything goes well except when I write

```
R CMD INSTALL monocle-release 
-bash: R: command not found

```
Is there a way to help direct this? I am a Mac OS High Sierra. 

Thanks,

Ode

**Comment by romanhaa** [comment]
Yep, you can install an older VGAM version manually but during the monocle3 installing process it will update it. I have the same issue as the previous posters.

**Comment by skurp** [comment]
I did not open a new issue because this thread is not labeled specifically to monocle 3, BUT in monocle 2 release I am running into the same error. `VGAM 1.0-6` is installed with the package distribution, but  `gaussianff()` is deprecated. I am not a statistician so I am not sure which newly named function will match the original function call.

**Comment by zbgaber** [comment]
I was having romanhaa's problem too.  I would manually reinstall VGAM 1.05 but when I installed monocle3, VGAM would update to 1.06.  I found that you could get around this using the argument dep = FALSE (tells devtools not to automatically update dependencies).

I also added argument force = TRUE, but I'm not sure if that's necessary.  

Anyways, after manually uploading VGAM 1.05 in console, using this code got me able to install monocle3:

devtools::install_github("cole-trapnell-lab/monocle-release", ref = "monocle3_alpha", force = TRUE, dep = FALSE)

**Comment by gexijin** [comment]
I also had a lot of trouble installing monocle 3. But eventually, I made it work.  Here is summary of what I did, partially based on the info above and other posts.
1.  Install an older version of VGAM. 
 remove.packages("VGAM")  # remove the 1.0-6
 download.files("https://cran.r-project.org/src/contrib/Archive/VGAM/VGAM_1.0-5.tar.gz", 
                         "VGAM_1.0-5.tar.gz")
 install.packages(""VGAM_1.0-5.tar.gz", repos = NULL, type = "source")

2. Install Rtools software in Windows. https://cran.r-project.org/bin/windows/Rtools/
  I don't know why, but even though a version of Rtools is installed under R3.5.1 folder. The path is messed up, as the compiler of monocle 3 tries to run C:\Rtools\....

3. Close Rstudio and moved to R itself, which uses C:\Rtools.   Rtools 3.5  does not work with R 3.5.1. Solve this with instructions from this page: https://github.com/r-lib/devtools/issues/1772

library(devtools)
assignInNamespace("version_info", c(devtools:::version_info, list("3.5" = list(version_min = "3.3.0", version_max = "99.99.99", path = "bin"))), "devtools")
find_rtools() # is TRUE now
devtools::install_github("r-lib/devtools")

4. Install monocle 3 from R (not Rstudio).
devtools::install_github("cole-trapnell-lab/monocle-release", ref = "monocle3_alpha", force = TRUE, dep = FALSE)

Worked for me.

**Comment by ciuhkimo** [comment]
@Xiaojieqiu , I tried to installed the 1.0-5 version, but I cannot install it. It showed that 
In R CMD INSTALL
* installing *source* package 'VGAM' ...
** package 'VGAM' successfully unpacked and MD5 sums checked
** libs


*** arch - i386
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'VGAM'
* removing 'C:/Program Files/R/R-3.5.1/library/VGAM'
* restoring previous 'C:/Program Files/R/R-3.5.1/library/VGAM'
Warning message:
In install.packages("~/Downloads/VGAM_1.0-5.tar.gz", repos = NULL,  :
  installation of package 'C:/Users/u1/Documents/Downloads/VGAM_1.0-5.tar.
gz' had non-zero exit status

**Comment by romanhaa** [comment]
@ciuhkimo You could start by looking up that error on Google and will find that the `make` command belongs the compiler libraries that you seem to be missing on your computer.

**Comment by liu2005678** [comment]
Try the following lines:
library(remotes)   # if "remotes" not installed, then install.packages("remotes") first
install_version("VGAM", version="1.0-5")
library(VGAM)
